name: Check advisories standalone
on:
  - push
  - pull_request
jobs:
  tools_changed:
    continue-on-error: true
    runs-on: ubuntu-22.04
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5.3.0
        with:
          concurrent_skipping: "never"
          skip_after_successful_duplicate: "true"
          paths: '["code/**"]'
          do_not_skip: '["push", "workflow_dispatch", "schedule"]'
  advisories_changed:
    continue-on-error: true
    runs-on: ubuntu-22.04
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5.3.0
        with:
          concurrent_skipping: "never"
          skip_after_successful_duplicate: "true"
          paths: '["advisories/**"]'
          do_not_skip: '["push", "workflow_dispatch", "schedule"]'
  check-advisories:
    name: Invoke check-advisories workflow
    needs: [tools_changed, advisories_changed]
    if: ${{ needs.tools_changed.outputs.should_skip == 'true' && needs.advisories_changed.outputs.should_skip != 'true' }}
    steps:
      - id: code-hash
        name: Compute code directory hash
        run: |
          code_hash=$(git rev-parse HEAD:code)
          echo "code-hash=$code_hash" >> "$GITHUB_OUTPUT"
      - uses: ./.github/workflows/check-advisories.yml
        with:
          fetch-key: hsec-tools-${{ steps.code-hash.outputs.code-hash}}
          is-artifact: false
          changed-advisories: ${{ toJSON(needs.advisories_changed.outputs.changed_files) }}
