name: nix build
on:
  - push
  - pull_request
jobs:
  tools_changed:
    continue-on-error: true
    runs-on: ubuntu-22.04
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5.3.0
        with:
          concurrent_skipping: "never"
          skip_after_successful_duplicate: "true"
          paths: '["code/**"]'
          do_not_skip: '["push", "workflow_dispatch", "schedule"]'
  check_nix:
    name: Check nix build
    needs: tools_changed
    if: ${{ needs.tools_changed.outputs.should_skip != 'true' }}
    uses: ./.github/workflows/call-nix.yml
  check-advisories:
    name: Invoke check-advisories workflow
    if: ${{ needs.tools_changed.outputs.should_skip != 'true' }}
    needs: check_nix
    uses: ./.github/workflows/call-check-advisories.yml
    with:
      fetch-key: hsec-tools-${{ github.sha }}
      is-artifact: true
