# Our desired pipeline using only a Nix shell environment
name: nix build

on:
  - push
  - pull_request
jobs:
  check_nix:
    name: Check nix build
    runs-on: ubuntu-22.04
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v4
        with:
          flake-lock-path: ./code/hsec-tools/flake.lock
      - run: nix -L build
        working-directory: ./code/hsec-tools
      - uses: actions/upload-artifact@v3
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        with:
          name: hsec-tools
          path: code/hsec-tools/result/bin/hsec-tools
